// Mocks generated by Mockito 5.4.2 from annotations
// in demo/test/billing_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i4;

import 'package:demo/model/billing.dart' as _i3;
import 'package:demo/provider/billing_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BillingProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockBillingProvider extends _i1.Mock implements _i2.BillingProvider {
  @override
  List<_i3.Billing> get billings => (super.noSuchMethod(
        Invocation.getter(#billings),
        returnValue: <_i3.Billing>[],
        returnValueForMissingStub: <_i3.Billing>[],
      ) as List<_i3.Billing>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setBillings(List<_i3.Billing>? newBillings) => super.noSuchMethod(
        Invocation.method(
          #setBillings,
          [newBillings],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeBilling(int? id) => super.noSuchMethod(
        Invocation.method(
          #removeBilling,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateBilling(_i3.Billing? billing) => super.noSuchMethod(
        Invocation.method(
          #updateBilling,
          [billing],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addBilling(_i3.Billing? billing) => super.noSuchMethod(
        Invocation.method(
          #addBilling,
          [billing],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
